from pathlib import Path
import hashlib,json
r=Path.cwd();own=r/'sub2api-transport-packaging-review';inputs=r/'.spike-inputs';helper=inputs/'candidate/sub2api-transport-packaging';pkg=inputs/'candidate/sub2api-transport-r4'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
outer=json.loads((inputs/'INPUT-HASHES.json').read_text())
assert all(sha(inputs/n)==h for n,h in outer.items())
for n,h in json.loads((helper/'artifact-hashes.json').read_text()).items():assert sha(helper/n)==h,n
old=(helper/'verify-provenance.py').read_text().replace("manifest=json.loads(checked_read(frozen,'INPUT-HASHES.json'))","manifest=json.loads((frozen/'INPUT-HASHES.json').read_text())").replace("    if any(ancestor.is_symlink() for ancestor in (target.absolute(), *target.absolute().parents)):\n        raise ValueError('historical symlink root or ancestor')\n",'')
assert hashlib.sha256(old.encode()).hexdigest()=='75b7d5742e00f8928799fa2206f86519b4ac1e1517bf3e429b7d950cb35148e1'
prior_review=json.loads((inputs/'previous-review/review.json').read_text())['frozen_hashes']
for name,h in prior_review.items():
 if any(name.endswith('/'+x) for x in ['prepare-standalone.py','audit.py','base-hashes.json','base-to-prior.delta.json','prior-hashes.json','runtime-hashes.json','output-hashes.json','adapter.mjs']) or '/overlay/' in name:
  assert sha(r/name)==h,name
binding={str(p.relative_to(r)):sha(p) for p in sorted(inputs.rglob('*')) if p.is_file()}
(own/'frozen-input-hashes.json').write_text(json.dumps(binding,indent=2)+'\n')
proposal={str(p.relative_to(pkg)):sha(p) for p in sorted(pkg.rglob('*')) if p.is_file()}
helpers={str(p.relative_to(helper)):sha(p) for p in sorted(helper.rglob('*')) if p.is_file()}
(own/'assembly-hashes.json').write_text(json.dumps({'proposal':proposal,'helper':helpers},indent=2)+'\n')
summary=json.loads((own/'evidence/verification.json').read_text()); cli=json.loads((own/'evidence/integrity-cli.json').read_text())
assert all(summary[k]['exit']==0 for k in ['audit','verify-provenance','prepare','node_packaging','goal_independent','goal_canonical'])
assert summary['python']=={'pass':11,'fail':0,'errors':0}
assert cli['failures']==cli['errors']==0 and len(cli['receipts'])==16
review={'verdict':'APPROVE','scope':'SOURCE ONLY, conditional on root obtaining actual current broker unmodified scanner PASS before adoption','source_findings':[], 'scanner_status':'PENDING actual broker capture; no scanner PASS or concrete denial supplied', 'required_before_adoption':'Root must capture and scan exact final 95-file proposal plus 37-file helper separately from original reports using actual current broker mark_reviewed; preserve all scanner findings. Fingerprints are insufficient.', 'assembly_binding':'assembly-hashes.json', 'frozen_input_binding':'frozen-input-hashes.json', 'input_manifest_sha256':sha(inputs/'INPUT-HASHES.json'),'inputs_verified':len(outer),'proposal_files':len(proposal),'helper_files':len(helpers),'helper_sha256':sha(helper/'verify-provenance.py'),'source_pin':'3004a4b16e03588ee62c0ed7fe2751e0e53300e0', 'tests':{'independent_integrity':4,'actual_cli_symlink_rejections':16,'zero_history_read_assertions':16,'structural':5,'python_packaging':11,'node_packaging':2,'goal_independent':4,'goal_canonical':45}, 'exact_reconstruction':{'base':102,'delta_paths':8,'prior':102,'runtime':103,'historical_output_entries':294,'historical_inputs':150,'plan':'unchanged against both retained plans'},'history':{'FAIL':11,'NOT RUN':9,'effects':686,'original_verdict':'REQUESTCHANGES','reexecuted':False}, 'limits':['Fixed-SHA Git execution only supplied root receipt; reviewer used extracted public base and mocked archive controls.','Public Git object authenticity and physical immutable archive bytes not independently authenticated.','No native engine, Go, Docker, network, providers, credentials, Git writes or subagents used.','User-supplied newer 20 memory FAIL and 12 cancel FAIL remain failures; raw newer native evidence not supplied here.','Future live engine gates NOT RUN; physical absolute intersample bound NOTPROVEN.','Historical retention hashes and receipt attribution preserved; stale receipt reference in input-retention.json is historical, not current scanner proof.'], 'owned_changes':'sub2api-transport-packaging-review/ only; reports, scripts and evidence; production source unchanged'}
(own/'review.json').write_text(json.dumps(review,indent=2)+'\n')
(own/'REPORT.md').write_text('''APPROVE source, conditional on root obtaining actual current broker unmodified scanner PASS for the exact final assembly before adoption. No new source defect found. Scanner remains PENDING in actual-root-gates.json; supplied fingerprints prove neither scanner execution nor PASS. No concrete scanner denial was supplied. Root must capture/scan the final exact 95-file proposal and 37-file helper, separately from original reports, and preserve scanner findings.

Repaired helper cb2624819941057b9b3cb61399e9f8354080830c0a2048acc327c76c40293a04 fixes original R1 root/ancestor and INPUT-HASHES symlink bypass. Independent real filesystem tests reject root, package ancestor, higher ancestor and manifest symlinks through both helper and installed provenance/audit entry points: 16 CLI rejections. Sixteen instrumented assertions prove rejection before any historical read for absolute and relative paths. Public-base verification still precedes historical verification; these assertions concern reads through the historical path, not prior public-base reads. Leaf symlink, corruption and unsafe-path controls pass. Removing exactly the two repair edits in memory reproduces frozen helper hash 75b7d5742e00f8928799fa2206f86519b4ac1e1517bf3e429b7d950cb35148e1; no legacy source copy is delivered.

All 295 outer input hashes and 36 helper ledger hashes verify. Source pin remains 3004a4b16e03588ee62c0ed7fe2751e0e53300e0. Exact reconstruction verifies 102 base files before delta access, eight unchanged delta paths, 102 prior files and 103 runtime files. Fresh installed prepare/plan, provenance and audit PASS against extracted base. Plan equals both retained plans. Audit verifies 294 historical output entries; provenance verifies 150 historical inputs and nested ledgers. Installed wrappers, retained originals, overlays, adapter, context/result/bounds/hash checks and fixed-SHA archive argv remain unchanged. No prior-code or runtime delivery tree is present.

Nearest regression checks: 11 Python packaging, two Node packaging, five structural and four independent integrity tests PASS. Numeric evidence independent checks: four PASS; current canonical evidence checks: 45 PASS. Python historical tests use a verified disposable pre-integration fixture; Node copies adapt path constants only. Production helper and installed wrapper bytes execute unchanged. All temporary fixtures were removed.

Retained history remains 11 FAIL / 9 NOT RUN, 686 attempts/effects and original REQUESTCHANGES; not rerun or promoted. User-supplied newer 20 memory FAIL / 12 cancel FAIL and native changes remain independent and unpromoted; raw newer evidence is absent here. Live engine gates NOT RUN; physical absolute intersample bound NOTPROVEN. Actual fixed-SHA Git preparation is supplied root receipt evidence only; public object authenticity and physical archive custody are not independently authenticated. Original archive fb5f52748ba6120fba9dbfcc34da43949c3c8ab1f2c8bf6203638458bfd849ec and newer root receipt claim 6e21fd05dccb0dfe217a6f5f39ccb9f8a1e2a7877c07fd616d5f14fef1c42114 remain distinct.

assembly-hashes.json binds every exact proposal/helper file; frozen-input-hashes.json binds all supplied inputs including original and R1 reviews. review.json and raw evidence record results and limits. Only sub2api-transport-packaging-review/ was authored. No production patch, scanner change, historical modification, Git write, Go/Docker/network/auth/key use or subagent. Source review complete; adoption remains conditional. STOP.
''')
artifacts={str(p.relative_to(own)):sha(p) for p in sorted(own.rglob('*')) if p.is_file() and p.name!='artifact-hashes.json'}
(own/'artifact-hashes.json').write_text(json.dumps(artifacts,indent=2)+'\n')
assert all(sha(inputs/n)==h for n,h in outer.items())
print(json.dumps({'verdict':review['verdict'],'source_only':True,'scanner':'PENDING','proposal_files':len(proposal),'helper_files':len(helpers),'artifacts':len(artifacts)}))
