import { readFile,writeFile,mkdir } from 'node:fs/promises';
import { spawn } from 'node:child_process';
const mode=process.argv[2];if(!['engine','direct','engine-none'].includes(mode))throw Error('Diagnostic mode required');
const cap=(await readFile('/client/capability','utf8')).trim();
const home='/client/home-'+mode;await mkdir(home);await mkdir(home+'/codex');
const env={PATH:process.env.PATH,LANG:'C.UTF-8',HOME:home,CODEX_HOME:home+'/codex',SPIKE_RUN_CAPABILITY:cap};
await writeFile(env.CODEX_HOME+'/config.toml',`model="mimo-v2.6-pro"\nmodel_provider="spike"\nweb_search="disabled"\n${mode==='engine-none'?'model_reasoning_effort="none"\n':''}[model_providers.spike]\nname="Run gateway"\nbase_url="http://tap:8787/${mode==='engine-none'?'engine':mode}/v1"\nenv_key="SPIKE_RUN_CAPABILITY"\nwire_api="responses"\nrequires_openai_auth=false\nrequest_max_retries=0\nstream_max_retries=0\nsupports_websockets=false\n`,{mode:0o600});
const source=await readFile('/checkout/sub2api-spike/run-client.mjs','utf8');
const prompt=/const prompt = ('[^\n]*');/.exec(source)?.[1];if(!prompt)throw Error('Pinned prompt unavailable');
const actual=JSON.parse('"'+prompt.slice(1,-1).replaceAll('"','\\"')+'"');
const args=['--ask-for-approval','never','exec','--sandbox','danger-full-access','--skip-git-repo-check','--json','--output-last-message',home+'/review.txt',actual];
const child=spawn('codex',args,{cwd:'/opt/rr-gateway-spike-fixture',env,stdio:['ignore','pipe','pipe']});
let stdout='',stderr='';const timeout=setTimeout(()=>child.kill('SIGKILL'),600000);
child.stdout.on('data',b=>{stdout+=b;if(stdout.length>16*1024*1024)child.kill('SIGKILL')});child.stderr.on('data',b=>{if(stderr.length<131072)stderr+=b});
const code=await new Promise(r=>child.on('close',r));clearTimeout(timeout);
await writeFile(home+'/events.jsonl',stdout,{mode:0o600});await writeFile(home+'/stderr.txt',stderr,{mode:0o600});
const events=stdout.split('\n').flatMap(l=>{try{return[JSON.parse(l)]}catch{return[]}});const review=await readFile(home+'/review.txt','utf8').catch(()=>'');
const receipt={mode,client:'Codex0.159.2',exit_code:code,agent_message_count:events.filter(e=>e.item?.type==='agent_message').length,successful_commands:events.filter(e=>e.type==='item.completed'&&e.item?.type==='command_execution'&&e.item.exit_code===0).length,turn_completed:events.some(e=>e.type==='turn.completed'),review_bytes:Buffer.byteLength(review),error_events:events.filter(e=>e.type==='error'||e.item?.type==='error').length,raw_secrets_exported:false};
await writeFile('/client/'+mode+'-summary.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));
